version: '3.3'

services:
  web:
    image: "fastapi_tdd"
    container_name: "fastapi_tdd"
    build:
      context: ./project
    volumes:
      - ./project:/app
    ports:
      - 5000:5000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://root:root@postgres_db:5432/web_dev
      - DATABASE_TEST_URL=postgres://root:root@postgres_db:5432/web_test
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres_db"
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root